openapi: 3.1.0
info:
  title: Pet Store API
  description: A sample Pet Store API for demonstrating Arazzo workflows
  version: 1.0.0
  contact:
    name: API Support
    email: support@petstore.example.com

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: user
    description: User operations
  - name: pet
    description: Pet operations
  - name: store
    description: Store operations
  - name: coupon
    description: Coupon operations

paths:
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful login
          headers:
            X-Rate-Limit:
              description: Calls per hour allowed by the user
              schema:
                type: integer
            X-Expires-After:
              description: Date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT authentication token
                  userId:
                    type: integer
                  username:
                    type: string
        '401':
          description: Invalid username/password

  /user/logout:
    post:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful logout

  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          required: true
          schema:
            type: string
            enum: [available, pending, sold]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '401':
          description: Unauthorized

  /pet/findByTags:
    get:
      tags:
        - pet
      summary: Finds Pets by tags
      operationId: findPetsByTags
      parameters:
        - name: tags
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

  /pet/{petId}:
    get:
      tags:
        - pet
      summary: Find pet by ID
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found

  /pet/{petId}/coupons:
    get:
      tags:
        - coupon
      summary: Get available coupons for a pet
      operationId: getPetCoupons
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  petId:
                    type: integer
                  coupons:
                    type: array
                    items:
                      $ref: '#/components/schemas/Coupon'
                  bestCouponCode:
                    type: string
                    description: The coupon code with the highest discount

  /store/order:
    post:
      tags:
        - store
      summary: Place an order for a pet
      operationId: placeOrder
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid order

  /store/order/{orderId}:
    get:
      tags:
        - store
      summary: Find purchase order by ID
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

  /store/inventory:
    get:
      tags:
        - store
      summary: Returns pet inventories by status
      operationId: getInventory
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Buddy
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          enum: [available, pending, sold]
        price:
          type: number
          format: float

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          enum: [placed, approved, delivered]
        complete:
          type: boolean
        couponCode:
          type: string
        totalPrice:
          type: number
          format: float
        discount:
          type: number
          format: float

    Coupon:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        discountPercent:
          type: integer
        validUntil:
          type: string
          format: date-time
